name: CMake Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install system dependencies
        run: sudo apt-get update -y && sudo apt-get upgrade -y && sudo apt-get install -y libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev pkg-config

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: Ninja
          buildPreset: Debug
